from django import forms

class SubmissionForm(forms.Form):
    YEAR_CHOICES = [(str(year), str(year)) for year in range(2024, 2019, -1)]
    TERM_CHOICES = [
        ('SPRING', 'SPRING'),
        ('SUMMER', 'SUMMER'),
        ('FALL', 'FALL'),
    ]
    COLLEGE_CHOICES = [
        ('ADMINISTRATION', 'ADMINISTRATION'),
        ('CENTER FOR ACADEMIC ENHANCEMENT', 'CENTER FOR ACADEMIC ENHANCEMENT'),
        ('AGRICULTURE', 'AGRICULTURE'),
        ('ARCHITECTURE (College)', 'ARCHITECTURE (College)'),
        ('ARCHITECTURE (School)', 'ARCHITECTURE (School)'),
        ('ASSOCIATE PROVOST FOR UNDERGRADUATE PROGRAMS', 'ASSOCIATE PROVOST FOR UNDERGRADUATE PROGRAMS'),
        ('ARTS & SCIENCES', 'ARTS & SCIENCES'),
        ('BUSH SCHOOL OF GOVERNMENT AND PUBLIC SERVICE', 'BUSH SCHOOL OF GOVERNMENT AND PUBLIC SERVICE'),
        ('MAYS BUSINESS', 'MAYS BUSINESS'),
        ('DENTISTRY (UNDERGRADUATE & GRADUATE) (College)', 'DENTISTRY (UNDERGRADUATE & GRADUATE) (College)'),
        ('DENTISTRY (PROFESSIONAL) (College)', 'DENTISTRY (PROFESSIONAL) (College)'),
        ('DENTISTRY (UNDERGRADUATE & GRADUATE) (School)', 'DENTISTRY (UNDERGRADUATE & GRADUATE) (School)'),
        ('DENTISTRY (PROFESSIONAL) (School)', 'DENTISTRY (PROFESSIONAL) (School)'),
        ('EDUCATION & HUMAN DEVELOPMENT (College)', 'EDUCATION & HUMAN DEVELOPMENT (College)'),
        ('EDUCATION & HUMAN DEVELOPMENT (School)', 'EDUCATION & HUMAN DEVELOPMENT (School)'),
        ('ENGINEERING', 'ENGINEERING'),
        ('TEXAS A&M UNIVERSITY AT GALVESTON', 'TEXAS A&M UNIVERSITY AT GALVESTON'),
        ('GEOSCIENCES (Pre-Fall 2022)', 'GEOSCIENCES (Pre-Fall 2022)'),
        ('SCHOOL OF LAW (UNDERGRADUATE & GRADUATE)', 'SCHOOL OF LAW (UNDERGRADUATE & GRADUATE)'),
        ('SCHOOL OF LAW (PROFESSIONAL)', 'SCHOOL OF LAW (PROFESSIONAL)'),
        ('LIBERAL ARTS (Pre-Fall 2022)', 'LIBERAL ARTS (Pre-Fall 2022)'),
        ('MEDICINE (UNDERGRADUATE & GRADUATE) (College)', 'MEDICINE (UNDERGRADUATE & GRADUATE) (College)'),
        ('MEDICINE (PROFESSIONAL) (College)', 'MEDICINE (PROFESSIONAL) (College)'),
        ('MEDICINE (UNDERGRADUATE & GRADUATE) (School)', 'MEDICINE (UNDERGRADUATE & GRADUATE) (School)'),
        ('MEDICINE (PROFESSIONAL) (School)', 'MEDICINE (PROFESSIONAL) (School)'),
        ('MILITARY SCIENCE', 'MILITARY SCIENCE'),
        ('NURSING', 'NURSING'),
        ('PHARMACY (PROFESSIONAL) (College)', 'PHARMACY (PROFESSIONAL) (College)'),
        ('PHARMACY (PROFESSIONAL) (School)', 'PHARMACY (PROFESSIONAL) (School)'),
        ('PUBLIC HEALTH', 'PUBLIC HEALTH'),
        ('TEXAS A&M UNIVERSITY AT QATAR', 'TEXAS A&M UNIVERSITY AT QATAR'),
        ('SCIENCE (Pre-Fall 2022)', 'SCIENCE (Pre-Fall 2022)'),
        ('PERFORMANCE, VISUALIZATION & FINE ARTS', 'PERFORMANCE, VISUALIZATION & FINE ARTS'),
        ('VETERINARY MEDICINE (UNDERGRADUATE & GRADUATE) (College)', 'VETERINARY MEDICINE (UNDERGRADUATE & GRADUATE) (College)'),
        ('VETERINARY MEDICINE & BIOMEDICAL SCIENCES (PROFESSIONAL) (College)', 'VETERINARY MEDICINE & BIOMEDICAL SCIENCES (PROFESSIONAL) (College)'),
        ('VETERINARY MEDICINE & BIOMEDICAL SCIENCES (UNDERGRADUATE & GRADUATE) (School)', 'VETERINARY MEDICINE & BIOMEDICAL SCIENCES (UNDERGRADUATE & GRADUATE) (School)'),
        ('VETERINARY MEDICINE & BIOMEDICAL SCIENCES (PROFESSIONAL) (School)', 'VETERINARY MEDICINE & BIOMEDICAL SCIENCES (PROFESSIONAL) (School)'),
        ('UNIVERSITY TOTALS', 'UNIVERSITY TOTALS'),
    ]

    year = forms.ChoiceField(choices=YEAR_CHOICES)
    term = forms.ChoiceField(choices=TERM_CHOICES)
    college = forms.ChoiceField(choices=COLLEGE_CHOICES)